### ISSUE TITLE
Longer location name gets displayed outside the event tile

### ISSUE THREAD

**Issue by WinsCodes** [memser-spaceport/pln-events#78]
Priority/Severity: Medium/Medium

Pre-requisites:
Create an event with its location attribute set as follows - 
location: TAUMATAWHAKATANGIHANGAKOAUAUOTAMATEATURIPUKAKAPIKI-MAUNGAHORONUKUPOKAIWHENUAKITNATAHU
[above is the longest place-name in the world :)]

Steps to reproduce:
1. Launch the Application Under Test url: https://events-qa.on.fleek.co/
2. On the timeline displayed, verify the event's location field

Expected result:
The event's location name should be displayed properly without any issues

Actual result:
The event's location name is displayed outside the event-tile

**Comment by Thangaraj-Ideas2it** [comment]
@WinsCodes  above is fixed. Please verify

**Comment by WinsCodes** [comment]
Verified in Sprint 3 - QA Build 003 and the issue still persists. 
Assigning back to you @Thangaraj-Ideas2it
